version: '3.6'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - SECRET_KEY='foo'
            - DJANGO_SETTINGS_MODULE=VPMS.settings
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
        ports:
            - "80:80"
